version: '3.8'

services:
  springboot:
    build:
      context: .
      dockerfile: Dockerfile-springboot
    container_name: springboot_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/demo
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=example
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:8
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: demo
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
